title : Jiang Ji
tagline: how many roads must a man walk down...
author :
  name : Jiang Ji
  email : jiang.ji@hotmail.com
  github : demote
  twitter : demotium
  feedburner : NONE

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
